# ---
# ComfyUI INSTARAW - NSFW Nodes Init
# ---

from .nsfw_detector import NODE_CLASS_MAPPINGS as DETECTOR_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as DETECTOR_DISPLAY_MAPPINGS
# Add this new import
from .propose_crop import NODE_CLASS_MAPPINGS as PROPOSER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PROPOSER_DISPLAY_MAPPINGS

# Combine mappings
NODE_CLASS_MAPPINGS = {
    **DETECTOR_MAPPINGS,
    **PROPOSER_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **DETECTOR_DISPLAY_MAPPINGS,
    **PROPOSER_DISPLAY_MAPPINGS,
}


__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]