# ---
# Filename: ../ComfyUI_INSTARAW/nodes/__init__.py
# ---

"""
ComfyUI INSTARAW Nodes
A collection of custom nodes by Instara
"""

from .api_nodes import (
    NODE_CLASS_MAPPINGS as API_NODE_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as API_NODE_DISPLAY_MAPPINGS,
)
from .utility_nodes import (
    NODE_CLASS_MAPPINGS as UTILITY_NODE_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as UTILITY_NODE_DISPLAY_MAPPINGS,
)
from .logic_nodes import (
    NODE_CLASS_MAPPINGS as LOGIC_NODE_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as LOGIC_NODE_DISPLAY_MAPPINGS,
)
from .interactive_nodes import (
    NODE_CLASS_MAPPINGS as INTERACTIVE_NODE_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as INTERACTIVE_NODE_DISPLAY_MAPPINGS,
)
from .nsfw_nodes import (
    NODE_CLASS_MAPPINGS as NSFW_NODE_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as NSFW_NODE_DISPLAY_MAPPINGS,
)
# This now correctly points to the new folder
from .output_nodes import (
    NODE_CLASS_MAPPINGS as OUTPUT_NODE_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as OUTPUT_NODE_DISPLAY_MAPPINGS,
)
from .input_nodes import (
    NODE_CLASS_MAPPINGS as INPUT_NODE_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as INPUT_NODE_DISPLAY_MAPPINGS,
)


# Combine all node mappings from different categories
NODE_CLASS_MAPPINGS = {
    **API_NODE_MAPPINGS,
    **UTILITY_NODE_MAPPINGS,
    **LOGIC_NODE_MAPPINGS,
    **INTERACTIVE_NODE_MAPPINGS,
    **NSFW_NODE_MAPPINGS,
    **OUTPUT_NODE_MAPPINGS,
    **INPUT_NODE_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **API_NODE_DISPLAY_MAPPINGS,
    **UTILITY_NODE_DISPLAY_MAPPINGS,
    **LOGIC_NODE_DISPLAY_MAPPINGS,
    **INTERACTIVE_NODE_DISPLAY_MAPPINGS,
    **NSFW_NODE_DISPLAY_MAPPINGS,
    **OUTPUT_NODE_DISPLAY_MAPPINGS,
    **INPUT_NODE_DISPLAY_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]