"""
INSTARAW API Nodes
External API integrations for ComfyUI
"""

from .generative_api_nodes import (
    NODE_CLASS_MAPPINGS as GENERATIVE_API_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as GENERATIVE_API_DISPLAY_MAPPINGS,
)
from .ideogram import (
    NODE_CLASS_MAPPINGS as IDEOGRAM_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as IDEOGRAM_DISPLAY_MAPPINGS,
)
from .gemini_native import (
    NODE_CLASS_MAPPINGS as GEMINI_NATIVE_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as GEMINI_NATIVE_DISPLAY_MAPPINGS,
)
from .grok_native import (
    NODE_CLASS_MAPPINGS as GROK_NATIVE_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as GROK_NATIVE_DISPLAY_MAPPINGS,
)
# --- ADD THIS IMPORT ---
from .flux_kontext import (
    NODE_CLASS_MAPPINGS as FLUX_KONTEXT_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as FLUX_KONTEXT_DISPLAY_MAPPINGS,
)
# --- END ADDITION ---
from . import creative_api


# Combine all API node mappings
NODE_CLASS_MAPPINGS = {
    **GENERATIVE_API_MAPPINGS,
    **IDEOGRAM_MAPPINGS,
    **GEMINI_NATIVE_MAPPINGS,
    **GROK_NATIVE_MAPPINGS,
    **FLUX_KONTEXT_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **GENERATIVE_API_DISPLAY_MAPPINGS,
    **IDEOGRAM_DISPLAY_MAPPINGS,
    **GEMINI_NATIVE_DISPLAY_MAPPINGS,
    **GROK_NATIVE_DISPLAY_MAPPINGS,
    **FLUX_KONTEXT_DISPLAY_MAPPINGS,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
